apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-ops
data:
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.163.cn:25
    user = k8s_mail@163.com
    password = 125800
    skip_verify = true
    from_address = k8s_mail@163.com
    [alerting]
    enabled = true
    execute_alerts = true