apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-ops
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: web
      port: 9091
      targetPort: 9090
      nodePort: 33000
    - name: alter2
      port: 9094
      targetPort: 9093
      nodePort: 33001
