# etcd 集群间通信的IP和端口, 根据etcd组成员自动生成
TMP_NODES: "{% for h in groups['etcd'] %}{{ hostvars[h]['NODE_NAME'] }}=https://{{ h }}:2380,{% endfor %}"
#去掉最后一个逗号 ETCD_NODES
ETCD_NODES: "{{ TMP_NODES.rstrip(',') }}"
# etcd_nodes etcd01=https://192.168.43.50:2380,etcd02=https://192.168.43.60:2380,etcd03=https://192.168.43.61:2380
ETCD_CHECK: "{% for h in groups['etcd'] %}https://{{ h }}:2380,{% endfor %}"
#https://192.168.1.21:2380, https://192.168.1.22:2380, https://192.168.1.23:2380
ETCD: "{% for h in groups['etcd'] %}https://{{ h }}:2379,{% endfor %}"
# 去掉最后面的一个逗号
ETCD_ENDPOINTS: "{{ ETCD.rstrip(',') }}"

NETWORK_CONFIG: '{"Network":"172.17.0.0/16","SubnetLen":24,"Backend":{"Type":"vxlan"}}'
ETCD_PREFIX: "/kube-centos/network"
