kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-prometheus-provisioner
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-prometheus-provisioner
    spec:
      serviceAccount: prometheus-nfs-provisioner
      containers:
        - name: nfs-prometheus-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner
          volumeMounts:
            - name: nfs-client-root-prometheus
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.7.3.31
            - name: NFS_PATH
              value: /k8s_nfs
      volumes:
        - name: nfs-client-root-prometheus
          nfs:
            server: 10.7.3.31
            path: /k8s_nfs

